OBJ=graph_basic.o graph_print.o graph_algos.o graphaux.o 
# version LINUX:
CC = g++
CCFLAGS = -g -DLINUX

all : Q1.exe Q2.exe Q3.exe


Q1.exe:
	$(CC) $(CCFLAGS) Q1.c $(OBJ) -lm -o Q1.exe

Q2.exe:
	$(CC) $(CCFLAGS) Q2.c $(OBJ) -lm -o Q2.exe

Q3.exe:
	$(CC) $(CCFLAGS) Q3.c $(OBJ) -lm -o Q3.exe
